<?php
/**
 * Auto generated by prado-cli.php on 2015-03-09 09:57:40.
 */
class CaixaRecord extends TActiveRecord
{

	
	const TABLE='caixa';

	public $codigo;
	public $data_abertura;
	public $data_fechamento;
	public $valor_inicial;
	public $valor_final;
	public $valor_sistema;

	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}
?>