<?php
/**
 * Auto generated by prado-cli.php on 2013-02-21 10:58:28.
 */
class CategoriasRecord extends TActiveRecord
{
	const TABLE='categorias';

	public $codigo;
	public $descricao;
		
			

	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
	
		/*Relacionamentos*/

	
	
}
?>