<?php
/**
 * Auto generated by prado-cli.php on 2015-03-09 09:00:56.
 */
class CondicoesPagamentosRecord extends TActiveRecord
{
	const TABLE='condicoes_pagamento';

	public $codigo;
	public $descricao;
	public $dias_credito;

	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}
?>