<?php
/**
 * Auto generated by prado-cli.php on 2010-10-18 08:56:38.
 */
class CozinhasRecord extends TActiveRecord
{
	const TABLE='cozinhas';
	public $codigo;
	public $descricao;
	public $impressora;
	public $imprimir_comanda;
	
	
	
	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
	public static $RELATIONS=array
    (
        'produtos' => array(self::BELONGS_TO,
            'ProdutosRecord', 'cozinhas_codigo'),
    );
}
 ?>
