<?php
/**
 * Auto generated by PRADO - WSAT on 2015-03-02 10:43:51.
 * @author                
 */
class FornecedoresProdutosRecord extends TActiveRecord 
{       
	const TABLE='fornecedores_produtos';

	public $pessoas_codigo;
	public $produtos_codigo;

	public static function finder($className=__CLASS__) {
                return parent::finder($className);
	}
                

                
	public function __toString() {
		return $this->produtos_codigo;
	}
}