<?php
/**
 * Auto generated by prado-cli.php on 2013-02-21 10:58:21.
 */
class InsumosRetiradosPedidosRecord extends TActiveRecord
{
	const TABLE='insumos_retirados_pedidos';

	public $sequencia;
	public $pedidos_codigo;
	public $produtos_codigo;
	public $item_pedido;
	
	
	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
	

	
}
?>