<?php
/**
 * Auto generated by prado-cli.php on 2013-02-21 10:58:21.
 */
class ItensPedidosRecord extends TActiveRecord
{
	const TABLE='itens_pedidos';

	public  $codigo; 			
	public  $produtos_codigo; 	
	public  $pedidos_codigo; 	
	public  $quantidade;		
	public  $valor;				
	public  $status_item;
	

	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
	
	
	public static $RELATIONS=array
    (
        'produtos' => array(self::BELONGS_TO,
            'ProdutosRecord', 'produtos_codigo'),
        'pedido' => array(self::BELONGS_TO,
            'PedidosRecord', 'pedidos_codigo'),
  
    );
	
}
?>