<?php
/**
 * Auto generated by prado-cli.php on 2013-02-21 10:58:31.
 */
class MenusRecord extends TActiveRecord
{
	const TABLE='menus';

	public $codigo;
	public $descricao;
	public $pagina;
	
	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}

	public static $RELATIONS=array
    (
        'roles' => array(self::MANY_TO_MANY,
            'RolesMenusRecord', 'menus_codigo'),
    );
	
	
}
?>