<?php
/**
 * Auto generated by prado-cli.php on 2013-02-21 10:58:31.
 */
class MovimentacoesConsumosPedidosRecord extends TActiveRecord
{
	const TABLE='movimentacoes_consumos_pedidos';

	public $codigo;
	public $produtos_codigo;
	public $itens_pedidos_codigo;
	public $quantidade_consumida;
	public $data_integracao;
	
	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
	
	public static $RELATIONS=array
    (
        'itens' => array(self::BELONGS_TO,
            'ItensPedidosRecord', 'itens_pedidos_codigo'),
        'produtos' => array(self::BELONGS_TO,
            'ProdutosRecord', 'produtos_codigo'),
    );	
}
?>