<?php
/**
 * Auto generated by PRADO - WSAT on 2015-03-02 09:57:35.
 * @author                
 */
class MovimentacoesFinanceirasRecord extends TActiveRecord 
{       
	const TABLE='movimentacoes_financeiras';

	public $codigo;
	public $documento;
	public $data_documento;
	public $valor_documento;
	public $data_vencimento;
	public $data_pagamento;
	public $valor_pago;
	public $forma_pagamento;
	public $tipo_movimento;
	public $observacao;
	public $pessoas_codigo;

	public static function finder($className=__CLASS__) {
                return parent::finder($className);
	}
                
	public static $RELATIONS=array
	(
			'pessoa' => array(self::BELONGS_TO,
					'PessoasRecord', 'pessoas_codigo'),
	);
	
                
	public function __toString() {
		return $this->documento;
	}
}