<?php
/**
 * Auto generated by prado-cli.php on 2013-02-21 10:58:28.
 */
class PessoasRecord extends TActiveRecord
{
	const TABLE='pessoas';

	public $codigo;
	public $cidades_codigo;
	public $razao_social;
	public $cnpj_cpf;
	public $insc_rg;
	public $endereco;
	public $bairro;
	public $cep;
	public $telefone;
	public $tipo_pessoa;
	public $celular;
	public $email;		
			

	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
	
		/*Relacionamentos*/
	public static $RELATIONS=array
    (
        'cidades' => array(self::BELONGS_TO,
            'CidadesRecord', 'cidades_codigo'),			
        
		
    );
	
	
	
}
?>