<?php
/**
 * Auto generated by prado-cli.php on 2013-02-21 10:58:21.
 */
class ProdutosRecord extends TActiveRecord
{
	const TABLE='produtos';

	public $codigo;
	public $tipos_produtos_codigo;
	public $engenharias_produtos_codigo;
	public $descricao;
	public $categorias_codigo;
	public $valor_compra;
	public $valor_venda;
	public $quantidade_minima;
	public $quantidade_estoque;
	public $cozinhas_codigo;
	public $data_exclusao;
	public $imagem;
	

	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
	
	
	public static $RELATIONS=array
    (
        'engenharia' => array(self::MANY_TO_MANY,
            'EngenhariaProdutosRecord', 'engenharias_produtos_codigo'),
		'categoria' => array(self::BELONGS_TO,
    				'CategoriasRecord', 'categorias_codigo'),
    		'cozinha' => array(self::BELONGS_TO,
    				'CozinhasRecord', 'cozinhas_codigo'),
    		
  
    );
	
}
?>
