<?php
/**
 * Auto generated by prado-cli.php on 2013-02-21 10:58:28.
 */
class TiposProdutosRecord extends TActiveRecord
{
	const TABLE='tipos_produtos';

	public $codigo;
	public $descricao;
	public $insumo;
	
			

	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
	
		/*Relacionamentos*/

	
	
}
?>