<?php
/**
 * Auto generated by prado-cli.php on 2010-10-18 08:56:38.
 */
class UsuariosRecord extends TActiveRecord
{
	const TABLE='usuarios';
	public $codigo;
	public $nome;
	public $username;
	public $passwd;
	public $data_exclusao;
	public $perc_comissao;
	
	
	
	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
	public static $RELATIONS=array
    (
        'roles' => array(self::MANY_TO_MANY,
            'UsuariosRolesRecord', 'usuarios_codigo'),
    );
}
 ?>
