<?php
/**
 * Auto generated by prado-cli.php on 2013-02-21 10:58:31.
 */
class UsuariosRolesRecord extends TActiveRecord
{
	const TABLE='usuarios_roles';

	public $usuarios_codigo;
	public $roles_codigo;

	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
	
	public static $RELATIONS=array
    (
        'usuarios' => array(self::BELONGS_TO,
            'UsuariosRecord', 'usuarios_codigo'),
        'roles' => array(self::BELONGS_TO,
            'RolesRecord', 'roles_codigo'),
    );	
}
?>