<?php
/**
 * Auto generated by prado-cli.php on 2013-02-21 10:58:31.
 */
class VendaProdutosAgrupadosRecord extends ItensPedidosRecord
{
	
	public $data;
	public $Hora;
	public $produtos;
	public $descricao;
	public $quantidade;

	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}

	
	
}
?>